# Generated by Django 4.1.7 on 2023-03-25 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_outlet', '0007_country_alter_address_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'get_latest_by': 'order_date', 'verbose_name_plural': 'Adress'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'countries'},
        ),
    ]
